export const FETCHING_RANDOM = "FETCHING_RANDOM";
export const FETCHED_RANDOM = "FETCHED_RANDOM";
export const ERROR_RANDOM = "ERROR_RANDOM";

export const FETCHING_LIST = "FETCHING_LIST";
export const FETCHED_LIST = "FETCHED_LIST";
export const ERROR_LIST = "ERROR_LIST";

export const FETCHING_POKE_IMAGES = "FETCHING_POKE_IMAGES";
export const FETCHED_POKE_IMAGES = "FETCHED_POKE_IMAGES";
export const ERROR_POKE_IMAGES = "ERROR_POKE_IMAGES";
