export const FETCHING_RANDOM = "FETCHING_RANDOM";
export const FETCHED_RANDOM = "FETCHED_RANDOM";
export const ERROR_RANDOM = "ERROR_RANDOM";

export const FETCHING_RANDOM_PNG = "FETCHING_RANDOM_PNG";
export const FETCHED_RANDOM_PNG = "FETCHED_RANDOM_PNG";
export const ERROR_RANDOM_PNG = "ERROR_RANDOM_PNG";

export const FETCHING_LIST = "FETCHING_LIST";
export const FETCHED_LIST = "FETCHED_LIST";
export const ERROR_LIST = "ERROR_LIST";

export const FETCHING_POKE_IMAGES = "FETCHING_POKE_IMAGES";
export const FETCHED_POKE_IMAGES = "FETCHED_POKE_IMAGES";
export const ERROR_POKE_IMAGES = "ERROR_POKE_IMAGES";

export const FETCHING_POKE_PNG = "FETCHING_POKE_PNG";
export const FETCHED_POKE_PNG = "FETCHED_POKE_PNG";
export const ERROR_POKE_PNG = "ERROR_POKE_PNG";

export const NEXT_LIST_PAGE = "NEXT_LIST_PAGE";
export const PREV_LIST_PAGE = "PREV_LIST_PAGE";
export const RESET_LIST_PAGE = "RESET_LIST_PAGE";

export const CHANGE_NUMBER_OF_POKEMON_PER_PAGE =
  "CHANGE_NUMBER_OF_POKEMON_PER_PAGE";
